# Generated by Django 5.1.3 on 2024-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_contacto', models.DateField()),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('fecha_examen', models.DateField()),
                ('entrenamiento_ingreso', models.DateField()),
                ('instructor', models.CharField(max_length=100)),
                ('en_servicio', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
